- id: clang-format
  name: clang-format (moved to https://github.com/pre-commit/mirrors-clang-format)
  description: clang-format your C, C++, or C# code
  entry: clang-format
  args: [-style=file, -i]
  language: python
  types_or: [c++, c, c#, cuda]
  minimum_pre_commit_version: 2.9.2
